import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { DotPattern } from "@/components/magicui/dot-pattern";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // FIXME: this is a temporary height
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#000]   overflow-x-hidden`}
      >
        <Navbar />

        {/*<div className=" flex  w-full flex-col items-center justify-center overflow-hidden  h-full absolute top-0 left-0">*/}
        {/*  <DotPattern*/}
        {/*    className={*/}
        {/*      "[mask-image:radial-gradient(59%_48%_at_center,white,transparent)]"*/}
        {/*    }*/}
        {/*  />*/}
        {/*</div>*/}
        {children}
      <Footer/>
      </body>
    </html>
  );
}
